"""empty message

Revision ID: e90ab45037da
Revises: 
Create Date: 2025-09-19 08:28:47.018512

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e90ab45037da'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tb_profissional',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('nome', sa.String(length=120), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('tb_servico',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('descricao', sa.String(length=120), nullable=False),
    sa.Column('valor', sa.Float(), nullable=False),
    sa.Column('horario_duraçao', sa.Float(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('tb_usuario',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('nome', sa.String(length=120), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('telefone', sa.String(length=50), nullable=False),
    sa.Column('senha', sa.String(length=120), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('tb_agendamentos',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('dt_agendamento', sa.DateTime(), nullable=False),
    sa.Column('dt_atendimento', sa.DateTime(), nullable=False),
    sa.Column('id_user', sa.Integer(), nullable=False),
    sa.Column('id_profissional', sa.Integer(), nullable=False),
    sa.Column('id_servico', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('valor_total', sa.Float(), nullable=False),
    sa.Column('taxa_cancelamento', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['id_profissional'], ['tb_profissional.id'], ),
    sa.ForeignKeyConstraint(['id_servico'], ['tb_servico.id'], ),
    sa.ForeignKeyConstraint(['id_user'], ['tb_usuario.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('tb_agendamentos')
    op.drop_table('tb_usuario')
    op.drop_table('tb_servico')
    op.drop_table('tb_profissional')
    # ### end Alembic commands ###
